#kind: pipeline
#name: default
#
#platform:
#  os: linux
#  arch: amd64
#
#steps:
#  - name: build
#    image: golang
#    commands:
#      - go build
#      - go test
#    when:
#      branch:
#        - master
#      event:
#        - push
#trigger:
#  branch:
#    - master
#  event:
#    - push

workspace:
  base: /go
  path: src/github.com/zhanghudong/drone-test

pipeline:
  build:
    image: golang:1.10.2
    commands:
      - go test
      - go build
