kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang
    commands:
      - go build
      - go test
    when:
      branch:
        - master
      event:
        - push
trigger:
  branch:
    - master
  event:
    - push

